image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [504.47676,   0.     , 321.61929,
           0.     , 505.40424, 243.0982 ,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.087060, -0.163208, -0.000412, 0.000303, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [508.99275,   0.     , 321.87692,   0.     ,
           0.     , 511.27639, 242.94459,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
