# USB
# teleop_twist_joy_node:
#   ros__parameters:
#     # Mecanum can strafe! So we map both X and Y linear axes.
#     axis_linear:
#       x: 1           # left stick up/down → forward/backward
#       y: 0           # left stick left/right → strafe left/right
#     scale_linear:
#       x: 0.5         # max linear X speed (m/s)
#       y: 0.5         # max linear Y speed (m/s)
#     scale_linear_turbo:
#       x: 1.0
#       y: 1.0

#     axis_angular:
#       yaw: 3         # right stick left/right → rotation
#     scale_angular:
#       yaw: 1.0       # max angular speed (rad/s)
#     scale_angular_turbo:
#       yaw: 2.0

#     enable_button: 4        # LB — hold to move
#     enable_turbo_button: 5  # RB — hold for turbo

#     # Official mecanum_drive_controller expects TwistStamped
#     publish_stamped_twist: true

# Bluetooth
teleop_twist_joy_node:
  ros__parameters:
    # Mecanum can strafe! So we map both X and Y linear axes.
    axis_linear:
      x: 1           # left stick up/down → forward/backward
      y: 0           # left stick left/right → strafe left/right
    scale_linear:
      x: 0.5         # max linear X speed (m/s)
      y: 0.5         # max linear Y speed (m/s)
    scale_linear_turbo:
      x: 1.0
      y: 1.0

    axis_angular:
      yaw: 2         # right stick left/right → rotation
    scale_angular:
      yaw: 1.0       # max angular speed (rad/s)
    scale_angular_turbo:
      yaw: 2.0

    enable_button: 6        # LB — hold to move
    enable_turbo_button: 7  # RB — hold for turbo

    # Official mecanum_drive_controller expects TwistStamped
    publish_stamped_twist: true